# Generated by Django 6.0.7 on 2026-07-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('desktop_image', models.ImageField(upload_to='hero/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='hero/mobile/')),
                ('button_one_text', models.CharField(blank=True, max_length=50)),
                ('button_one_url', models.CharField(blank=True, max_length=255)),
                ('button_two_text', models.CharField(blank=True, max_length=50)),
                ('button_two_url', models.CharField(blank=True, max_length=255)),
                ('overlay_opacity', models.PositiveSmallIntegerField(default=50)),
                ('display_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
