# Generated by Django 6.0.7 on 2026-07-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herobanner',
            options={'ordering': ['display_order'], 'verbose_name': 'Hero Banner', 'verbose_name_plural': 'Hero Banners'},
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='desktop_image',
            field=models.ImageField(upload_to='company/hero/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/hero/mobile/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
