# Generated by Django 6.0.7 on 2026-07-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_herobanner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=250)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('image', models.ImageField(upload_to='company/about/')),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('experience_years', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'About Company',
                'verbose_name_plural': 'About Company',
            },
        ),
    ]
