# Generated by Django 6.0.7 on 2026-07-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_aboutcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Bootstrap Icon class, e.g. bi bi-robot', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Why Choose Us',
                'verbose_name_plural': 'Why Choose Us',
                'ordering': ['display_order'],
            },
        ),
    ]
