# Generated by Django 6.0.7 on 2026-07-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_achievement_contactinfo_partner_seosetting_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='number',
        ),
        migrations.AddField(
            model_name='achievement',
            name='suffix',
            field=models.CharField(default='+', help_text='Examples: +, %, Years', max_length=5),
        ),
        migrations.AddField(
            model_name='achievement',
            name='value',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
