# Generated by Django 6.0.7 on 2026-07-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_achievement_number_achievement_suffix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partnership_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
