# Generated by Django 6.0.7 on 2026-07-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_service_options_service_full_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
