# Generated by Django 6.0.7 on 2026-07-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_testimonial_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceinquiry',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceInquiry',
        ),
    ]
